# Generated by Django 3.0.3 on 2020-04-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='employment',
            field=models.CharField(default='Unemployed', max_length=30),
        ),
    ]
