# Generated by Django 3.0.3 on 2020-04-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200416_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='employment',
            field=models.CharField(default='Unspecified', max_length=30),
        ),
    ]
